# Site CONSTANTS ===================================================== #

constants:

  # Locale and encoding
  dir: rtl
  lang: en-US
  locale: en_US
  encoding: utf-8
  viewport: width=device-width

  # Name (Brand), Tagline and Meta Image (Og)
  name: Jhaura Wachsman
  tagline: Web Developer
  description: |
    Jhaura Wachsman is a web developer who delivers modern mobile-first web applications using today's most advanced technologies and techniques so that your website delivers an exceptional user experience.

  # Contact and Domain
  email: jw@jhaurawachsman.com
  domain: jhaurawachsman.com

  # Social Media User Names (Not full URL)
  github: jhauraw
  twitter: JhauraWachsman
  facebook: JhauraWachsman
  gplus: 103492502746159725544
  pinterest: jhaurawachsman
  linkedin: jhaurawachsman

  # Feedburner Feed Name
  feed-name: jhaurawachsman

  # Meta Admin / Verify IDs
  facebook-admin: 1550453047
  facebook-appid: 251689391563684
  gplus-publisher: 103492502746159725544
  disqus-user:

  # Analytics / Metrics
  google-analytics-id: UA-17276272-1

  # Default author for Posts
  author:
    name: Jhaura Wachsman
    domain: jhaurawachsman.com

# Jekyll Config ====================================================== #

auto: false
server: false

# Used any place a where an absolute URL is required.
#
# REQUIRED if you want OG:TYPE meta tags, XML feed and
# robots.txt sitemap link.
#
# If using jekyll --server locally, use: http://localhost:PORT
# Default PORT is usually 4000
#
# If using MAMP/XAMP locally, use your local host name such as
# sitename.localhost
#
# For production, set to the HTTP server domain.
# Be sure to use http://
#
# NO Trailing-Slash
url: http://localhost:4000

# To run the ENTIRE site from a sub-dir, e.g., /sub
# YES Front-Slash. NO Trailing-Slash
#
# This theme uses ABSOLUTE URLs in places like the XML Feed and
# OG tags, so we need to set it to '' (empty) explicitly so
# that the Jekyll default of '/' doesn't mess up our URLs with
# // (double-slashes).
#
# YES Front-Slash. NO Trailing-Slash
baseurl: null

# Not a part of Jekyll, but adding it here for grouping with
# other base* and url* configs.
#
# Abstracts hardcoded image directory names out of the templates.
#
# In your YAML Front Matter reference images by a relative URL,
# such as:
# image.jpg
# YEAR/image.jpg
# CATEGORY/image.jpg
#
# In your Templates prepend any {{ page.img.url }} tags with:
#
# If you prefer ROOT RELATIVE URLS:
# {{ site.baseurl }}{{ site.baseimg }}
#
# If you prefer ABSOLUTE URLS:
# {{ site.url }}{{ site.baseurl }}{{ site.baseimg }}
#
# Now your templates, posts and pages will be fully abstracted
# in terms of URL/Directory structure. *Smile* :-)
#
# YES Front-Slash. YES Trailing-Slash
baseimg: /img/

# You can use a directory name here to have just the _posts
# served from an sub-directory, e.g., /blog/
#
# In that case, your permalink value might be: /blog/:title/
#
# NOTE: This is different from the baseurl variable above;
# as it only affects the _posts directory, a.k.a., Blog.
#
# YES Front-Slash. YES Trailing-Slash
permalink: /blog/:title/

#lsi: true
markdown: redcarpet
pygments: true
paginate: 10

include: ['.htaccess']
exclude: ['CHANGELOG.md', 'README.md', 'LICENSE', 'Gruntfile.js', 'package.json', 'node_modules', 'bower_components']
